#!/bin/bash
#
# A quick smoke-test of Lambkin.
#
# Creates, publishes, runs and crons a basic function in Python and another
# in Node.js.

set -eou pipefail

for runtime in python node; do
  func=${runtime}-smoketest
  lambkin list-published | grep -q ${func} && lambkin unpublish ${func}
  rm -rf ${func}
  lambkin create ${func} $([[ ${runtime} == python ]] || echo --runtime=${runtime})
  lambkin make ${func}
  lambkin publish ${func} --description="${runtime} smoke test function" | jq '{runtime: .Runtime}'
  lambkin run ${func} | jq .
  lambkin schedule ${func} --rate '5 minutes' | jq '{status: .ResponseMetadata.HTTPStatusCode}'
  lambkin unpublish ${func}
  rm -rf ${func}
  echo
done
