#!/bin/bash
#
# A quick smoke-test of Lambkin.
#
# Creates, publishes, runs and crons a basic function in Python and another
# in Node.js.

set -xeou pipefail

for runtime in python node; do
  func=${runtime}-smoketest
  lambkin list-published | grep -q ${func} && lambkin unpublish --function=${func}
  rm -rf ${func}
  lambkin create ${func} $([[ ${runtime} == python ]] || echo --runtime=${runtime})
  cd ${func}
  echo 'requests' >> requirements.txt
  lambkin build
  lambkin publish --description="lambkin smoketest - ${func}"
  lambkin run | jq .
  lambkin schedule --rate '5 minutes' | jq '{status: .ResponseMetadata.HTTPStatusCode}'
  lambkin schedule --cron '* * * * ? *' | jq '{status: .ResponseMetadata.HTTPStatusCode}'

  lambkin unpublish
  cd ..
  rm -rf ${func}
  echo
done
