{{function_name}}:
	@echo "make" called for {{function_name}}

	# Install some Python libraries.
	# pip install requests -t .
	# pip install elasticsearch -t .

	# Or maybe we're hacking NodeJS. Here's how to bundle npm packages.
	# npm install --prefix=. aws-sdk
	# npm install --prefix=. js-yaml
